name: Bandit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: read
  statuses: write
  security-events: write

jobs:
  build:
    name: Bandit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
